@SurveyBasket.API_HostAddress = https://localhost:7023

GET {{SurveyBasket.API_HostAddress}}/api/polls // Connect to Internet 

###

@id=0
DELETE {{SurveyBasket.API_HostAddress}}/api/polls/{{id}}

###
