@SurveyBasket.API_HostAddress = https://localhost:7023

POST {{SurveyBasket.API_HostAddress}}/api/auth
Content-Type: application/json

{
  "email":"yousef@gmail.com",
	"password":"P@ssowrd2005"
}

###

GET {{SurveyBasket.API_HostAddress}}/health


POST {{SurveyBasket.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName":"Yousef",
  "lastName":"Mohamed",
  "email":"yousef@gmail.com",
	"password":"P@ssowrd2005"
}

###

POST {{SurveyBasket.API_HostAddress}}/api/auth/confirm-email
Content-Type: application/json

{
  "code":"Q2ZESjhGSUVoblRHbDF4SW9jSXI5Ui9VcWtEZXJuWU41TDJkMUlrQVQ4NmVjeTc2cThYV2pTMUc2RTFqYlBCc2tjMXJtM0hRbER1b2JKR3ptdjRvZWxBVlZNYVBYWElzS3o5QkZVRmRjWmErMWtjSldBMkpsdi9KV3g5UHB3MDNUTFN4OWw3R01QeGZWN2x4d2ZNOVZMeWpvc3pxOTRIUmJqS2NjVUJRNEhiMDVLS0RVQmdHU05GRzhpTzBWYWR3akFZejFHYzBQNStlakRmNGpkM1REeEVya0loR3h6c2s2NWFrU1ZxdVdqanNyZkdIUFlBSDcweG8wYTR0Mk9EdW15c3hIdz09"
}

###
